---
title: "Aufgabe Eins - Lingster Akadamie"
format: html
editor: visual
bibliography: references.bib
csl: apa.csl 
---

### Inserting Umlauts

-   [Insert special characters using *standard HTML code*](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references)

-   **Umlaut formula**: **`&[letter]uml;`**

    -   E.g.: Herr Müller sagt: "Über den Wolken können Sonnenuntergänge besonders schön sein."

-   **Eszett formula**: **`&szlig;`**

    -   E.g.: Großartig

# Ubung von Linkster Akadamie

### Module 1.1

Für jedes wort, das du lernen möchtest, *kreierst* du ein Bild im Kopf.

-   Neue wörter

    -   *einschätzen* = bedeutet assess\
    -   *erstelle*; *kreierst* = bedeutet create\
    -   *zunächst* = bedeutet *at first*\
    -   *Erscheinungs* bild = bedeutet appearance\
    -   *auffallen*; Er *fällt* mit seinen 1.766 m gross sofort auf.
    -   *Umfeld:* = bedeutet environment\
    -   *Scheidung eingereichen*; sie hat eine Scheidung eingereicht.
    -   *Eingehörige* = bedeutet relatives\
    -   *Einsigartig;* = bedeutet unique

-   Kreiere mit diesen Wörtern eine Geschichte.

-   Jedes der Wörter sollte mindistens 1-2 Mal vorkommen.

-   Übe all vier Fertigkeiten damit:

    -   Sprechen, Scrheiben, Lesen und Hören

-   Zunächst, erfindest die Geschichte in deinen Kopf;

    -   und sagte dir laut vor

-   Danach, schreibst du die auf

-   Achtung: Es geht nur für die wörter und nicht um die Grammatik;

-   Machsts du am besten eins, zwei oder dreimal.

::: callout-note
*Merke dir*: Du brauchsts 7 bis 10 Begegnungen pro Wort; damit du langfristig im deinem Wortschatz aufnehmen und du selbst benutzt.
:::

### Module 1.2: Das Wesen der Menschen

-   Neue wörter
    -   verhaltensweisen - behavior
        -   Unserer Charakter ist die Summa unserer **Verhaltensweisen**; er definiert unser **Wesen**
    -   *nachschlagen:* = *Schlage* die unbekannten Wörter *nach*!
    -   *Großzugig* = bedeutet generous
    -   *verraten* = bedeutet revealed; as in "giving away a secret or betraying a trust.
        -   Auf dem ersten Bild **verrät** der Gesichtsausdruk des mannes, das er traurig ist.\
        -   Ich verrate dir mein Passwort.\
    -   *Enthüllen* = bedeutet "uncover" in a positive sense; ;uncovering the truth.  
    -   *Ungeheurerlichen* = bedeuttet "outrageous"  

::: callout-note
Das *enthüllen* dazu dient, etwas aufzudecken, das zuvor verborgen oder unbekannt war, während *verraten* bedeutet, Informationen preiszugeben oder das Vertrauen einer Person zu verraten.
:::

-   Weitere Wörter, die in der ersten Lektion vorkommen sind:

    -   *Gesichtsausdruk*, *nachdenklichen*, *wütenden*\
    -   *schief* bedeutet awry. z.B. " Vermutlich läuft etwas auf seiner Arbeit *schief*. "
    -   *eigenschaften* z.B. Die Eigenschaften der vier Personen, diese sind die Traurigkeit, die Wt und die Skepsis. a
    -   *Bedruckten* bedeutet 'dejected', z.B. Auf dem ersten Foto sehe ich einen *bedrückten* Mann, der vermutlich von seiner Frau verlassen wurde und der sich einsam fühlt.\
    -   *Durftig* bedeutet poor. z.B. Mein Wortschatz ist immer noch sehr d&uumlrftig.\
    -   *Ausdauer* bedeutet endurance. Typisch menschliche positive Eigenschaften sind *Entschlusskraft* (determination) und *Ausdauer*.
    -   *Annäherung* bedeutet rapprochement
    -   *Umsetzung* bedeutet implimentation:
        -   *Wir haben kein Erkenntnisproblem, wir haben ein Umsetzungsproblem*, Claudia Kemfert (2023)[@wirha2023]
        -   

# Ubung von *Easy German* 

### Untrennrare Verben mit *VER-* als Pr&auml;fix im Deutschen. 

::: {.callout-note collapse="true"}
YouTube program [*Easy German*](https://www.youtube.com/watch?v=hR5jz_QQ-NI)  
Gibt es eine Verkn&uuml;pfung zwischen all den Verben mit *ver*?   
Hat *ver-* eine Bedeutung?  Das ist nicht so zufriedenstellend, aber "Ja" und "Nein" kann man sagen.  
Die Antwort is komplezirt.  Man kann in der [Blog von Emanual](www.yourdailygerman.com) die Antwort finden. Er erz&auml;hlt woher dieses *ver* kommpt.  

Ver gibt so ein Gef&uuml;hl, das man hat.  
* Von etwas geht weg,  
* etwas verschwinded, 
* eine Bewegung weg von euch.  

:::

* Erste Gruppe - das etwas falsch gemacht wird  
  - Wenn etwas fasch l&auml;uft, wenn etwas schief l&auml;uft.  
  - l&auml;ufen:  Janusz l&auml;uft auf der stra&szlig;e = walk  
  - Wenn man **verl&auml;uft**, heisst er wei&szlig; nicht wo er hinwollte; er ist in die falsche Richtung gegangen. 
  - *Schreiben*  
  - Wenn man **verschreibt sich** hei&zslig;t er hat etwas falsch gescrieben. 
  - **W&auml;hlen** = To dial a number
  - Jetz hat Janusz sich **verw&auml;ht** =  Misdialed, 
    - **Verw&auml;hlen** hei&szlig;t, das Janusz die falsche Nummer angeruffen hat.  
 
 - Janusz **legt** seine Kamera auf den tisch.  
 - Janusz hat siene Kamera **verlegt**, das hei&szlig;t, er wei&szlig; nicht mehr wo er sie hingelegt hat.  Die Kamera ist weg.   
 
 - Janusz schluckt etwas, zum Beispiel schluckt er eine Tablette.  
 - Aber wenn man **verschluckt**, (schluckt der falsche weg) dann hat man nicht richtig geschluckt, dann ist zum Beispiel Wasser in die Luftr&ouml;hre gekommen.  
 
 * Verben mit ver sind etwas falsch gelaufen sind, or sogar verloren gegangen sind.  
 
 * Zweite Gruppe:  
 
In der zweiten Gruppe gibt es immer etwas, was verschwindet, was weg geht, was aufh&ouml;rt order was stoppt.   
 - Wenn ich etwas kaufe, dann kaufe ich es zu mir.  
 - Wenn ich etwas **verkaufe**, es ist weg dann, danach.   
 - Wenn ich **wette**, dann setze ich Geld auf eine bestimmte Chance, dass etwas passiert.  
 - Wenn ich alles **vervettte**, ich hab mein ganzes Geld verwettet, dan ist es weg.  
 - Januszs Kamera ist **verschwunden**.  Man findet sie nicht mehr wieder.   
 - Ich **verliere** etwas.  Janusz hat seine Kamera verloren.  
 - Ich habe das Konzert verpasst.  Ich konnte nicht zum Konzert gehen.  
 - **Versetzen**:  To stand up.  
 - **Verabredet**  Ich habe mit Janusz verabredet, aber ich bin nicht gekommen.  Ich hab' auch nicht angerufen.  
 
Die Verben mit *ver* immer mit, dieser Bewegung verkn&uuml;pfen kann, oder mit dieser Idee verkn&uuml;pfen kann, 
(verkn&uuml;pfen bedeutet *link*) .  

Etwas verschwindet, weg von einen, verliert, 
 
* Dritte Gruppe 

*ver* etwas wie eine langfristige oder nachhaltigere Ver&auml;nderung ausdr&uuml;ckt.  
Diese worter geben ein Gef&uuml;hl das etwas grunds&auml;tlich jver&auml;ndert.  
 
**Versuchen** to try  
**Ver&auml;ndern** = to change  
**Verschieben** = to move  
**Verhandeln, vertrauen und verstehen**  


 
  
  
### References
